config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {:omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations"}

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Forem::Engine, :at => '/forum'

  root 'home#index'
  resources :pages do
    collection do
      get 'category'
      get 'states'
      get 'reference'
      get 'wheat'
      get 'maize'
      get 'rice'
      get 'pulses'
      get 'jute'
      get 'sugarcane'
      get 'nuts'
      get 'sand'
      get 'seasons'
      get 'debt_relif'
      get 'short_term_loan'
      get 'midloan'
      get 'agri_banking'
      get 'agri_credit'
      get 'populate_state'
      get 'education'
    end
  end
  resources :states

offline = Rack::Offline.configure :cache_interval => 120 do 
  cache ActionController::Base.helpers.asset_path("application.css")
  cache ActionController::Base.helpers.asset_path("application.js")
  cache ActionController::Base.helpers.asset_path("desktop.css")
  cache ActionController::Base.helpers.asset_path("desktopd7b7.css")
  cache ActionController::Base.helpers.asset_path("ipad.css")
  cache ActionController::Base.helpers.asset_path("ipadv.css")
  cache ActionController::Base.helpers.asset_path("phonehorizontal.css")
  cache ActionController::Base.helpers.asset_path("phonevertical.css")
  cache ActionController::Base.helpers.asset_path("themes/alertnate-texture-body-bottom.png")
  cache ActionController::Base.helpers.asset_path("themes/alertnate-texture-body-full-bottom.png")
  cache ActionController::Base.helpers.asset_path("themes/alertnate-texture-body-full-top.png")
  cache ActionController::Base.helpers.asset_path("themes/alertnate-texture-body-full.jpg")
  cache ActionController::Base.helpers.asset_path("themes/alertnate-texture-body-top.png")
  cache ActionController::Base.helpers.asset_path("themes/alertnate-texture-body.jpg")
  cache ActionController::Base.helpers.asset_path("themes/background-overlay.png")
  cache ActionController::Base.helpers.asset_path("themes/background-texture-1.jpg")
  cache ActionController::Base.helpers.asset_path("themes/coupon-texture-1.jpg")
  cache ActionController::Base.helpers.asset_path("themes/content-background.jpg")
  cache ActionController::Base.helpers.asset_path("themes/header-texture-1.jpg")
  cache ActionController::Base.helpers.asset_path("themes/main-menu-texture-1.jpg")
  cache ActionController::Base.helpers.asset_path("themes/coupon-overlay.png")
  cache ActionController::Base.helpers.asset_path("agri-snapshot.png")
  cache ActionController::Base.helpers.asset_path("agri_credit.jpg")
  cache ActionController::Base.helpers.asset_path("debt.jpg")
  cache ActionController::Base.helpers.asset_path("education.jpg")
  cache ActionController::Base.helpers.asset_path("facebook.png")
  cache ActionController::Base.helpers.asset_path("fb-logo.png")
  cache ActionController::Base.helpers.asset_path("growth.jpg")
  cache ActionController::Base.helpers.asset_path("home.jpg")
  cache ActionController::Base.helpers.asset_path("indiarice.png")
  cache ActionController::Base.helpers.asset_path("jute.jpg")
  cache ActionController::Base.helpers.asset_path("loans.jpg")
  cache ActionController::Base.helpers.asset_path("logo.png")
  cache ActionController::Base.helpers.asset_path("maize.jpg")
  cache ActionController::Base.helpers.asset_path("maizeindia.png")
  cache ActionController::Base.helpers.asset_path("midloan.jpg")
  cache ActionController::Base.helpers.asset_path("nuts.jpg")
  cache ActionController::Base.helpers.asset_path("pulses.jpg")
  cache ActionController::Base.helpers.asset_path("rice.jpg")
  cache ActionController::Base.helpers.asset_path("sands.jpg")
  cache ActionController::Base.helpers.asset_path("season.jpg")
  cache ActionController::Base.helpers.asset_path("spices.jpg")
  cache ActionController::Base.helpers.asset_path("sugarcane.jpg")
  cache ActionController::Base.helpers.asset_path("wheat.jpg")


network "/"
end


get "/application.manifest" => offline


end

app/views/shared/_flash_message.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <%= content_tag :div, msg, :id => "flash_#{name}", :style => 'display:inline;' %>
      <a class="close" data-dismiss="alert">&#215;</a>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-copyright">
  <div class="wrapper">
    <!-- <div class='right'> -->
      <div class='row'>
        <div class='col-md-10' style='margin-top: 10px;'>
          <p>© 2015 Copyright <b>Agriculture Database</b>. All Rights reserved.</p>
        </div>
        <div class='col-md-2 right' style='text-align:right;'>
          <div class='facebook'>
            <%= link_to '<i class="fa fa-facebook-square fa-3x"></i>'.html_safe, "https://www.facebook.com", target: '_blank' %>
          </div>
          <div class='twitter'>
            <%= link_to '<i class="fa fa-twitter-square fa-3x"></i>'.html_safe, "https://www.facebook.com", target: '_blank' %>
          </div>
          <div class='google'>
            <%= link_to '<i class="fa fa-google-plus-square fa-3x"></i>'.html_safe, "https://www.facebook.com", target: '_blank' %>
          </div>
        </div>
      </div>
    <!-- </div> -->
  </div>
</div>

<style type="text/css">
  .facebook {
    display: inline-block;
    margin-right: 5px
  }

  .twitter {
    display: inline-block;
  }

  .google {
    display: inline-block;
    margin-left: 5px
  }

  .facebook > a {
    color: #3b5998;
    text-decoration: none;
  }

  .facebook > a:hover {
    color: #CA9469;
    text-decoration: none;
  }

  .twitter > a {
    color: #1dcaff;
    text-decoration: none;
  }

  .twitter > a:hover {
    color: #CA9469;
    text-decoration: none;
  }

  .google > a {
    color: #D50F25;
    text-decoration: none;
  }

  .google > a:hover {
    color: #CA9469;
    text-decoration: none;
  }
</style>

app/views/shared/_header.html.erb
<div class="header">
  <div class="wrapper col-md-12">
    <div class='row'>
      <div class='col-md-9' style='margin-top:10px'>
        <div class='row'>

          <div class="col-md-2 logo-header" style='padding-right: 0px;width: 13.666667%;'>
            <a href="<%= root_path %>" class="logo-image" style='margin-top: 0%'>
              <%= image_tag 'logo.png', border: '0px', size: '100x100' %>
            </a>
          </div>
          <div class='col-md-10' style='margin-top: 4%;padding-left: 0px;'>
            <h3>
              <a href="<%= main_app.root_path %>" style='text-decoration: none'>
                Farming enhancement through Information and Communication Technology- Website design for rural farmers
              </a>
            </h3>

          </div>
        </div>
      </div>
      <div class="col-md-3 header-featured weather-fore" style='text-align: center;display:block; padding-top: 26px;padding-left: 30px;'>
        <div class="featured-content">
          <% forecast = ForecastIO.forecast(51.5000, 0.1167) %>
          <h3><a href="#"><i class="wi wi-thermometer"> Weather Forecast </i> </a></h3>
          <h4>
			  <span class='forecast'> 
				Temp:
          <%= forecast.currently.temperature %>
          <i class="wi wi-day-lightning"></i>
          <%= forecast.currently.summary %>
			 </span>
          </h4>
          <h4>
			  <span class='forecast'> 
				Date:
          <%= Time.now.strftime('%d %b-%Y') %>
          <!-- <div class='col-md-6 weather-time' style='width:75%;'></div> -->
			  </span>
          </h4>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_nav_bar.html.erb
<div class="very-top">
  <div class="wrapper">
    <ul class="left" rel="Top Menu">
      <li id="menu-item-582" class="menu-item menu-item-type-post_type menu-item-object-page single">
        <!-- <a href="#"> </a> -->
        <!-- <div class='col-md-6 weather-time' style='width:100%;'></div> -->
      </li>
    </ul>
    <ul class="right" style='margin-bottom: 0px;'>
      <li>
        <div id="google_translate_element"></div>
      </li>
      <% if user_signed_in? %>
        <li>  <%= link_to current_user.email, '#', style: 'text-decoration: none;' %> </li>
        <li> <%= link_to 'Sign out', main_app.destroy_user_session_path, :method => 'delete', role: 'menuitem', tabindex: '-1' %> </li>
      <% else %>
        <li>  <%= link_to 'Sign in', '#', id: 'user-sign-in', style: 'text-decoration:none;' %> </li>
        <li> <%= link_to 'Sign up', main_app.new_user_registration_path, style: 'text-decoration:none;' %> </li>
      <% end %>
    </ul>
    <div class="clear-float"></div>
  </div>
</div>

<script type="text/javascript">
  function googleTranslateElementInit() {
    new google.translate.TranslateElement(
        {pageLanguage: 'en', includedLanguages: 'en,hi,kn,ml,ta,te'},
        'google_translate_element'
    );
    jQuery('.goog-logo-link').css('display', 'none');
    jQuery('.goog-te-gadget').css('font-size', '0');
    jQuery('.goog-te-combo').addClass('form-control');
  }
</script>

<%= render 'shared/popup/sign_in' %>

<script type="text/javascript">
  $('#user-sign-in').click(function () {
    $('#sign-in-modal').modal('show');
  });
  $('#user-sign-up').click(function () {
    $('#sign-up-modal').modal('show');
  });
</script>

app/views/shared/_nav_bar_new.html.erb
<div class="main-menu">
  <div class="wrapper">
    <ul class="menu" rel="Main Menu">
      <li id="menu-item-20" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-15 current_page_item <%= 'menu_active' if controller_name == 'home' && action_name == 'index' %>">
        <%= link_to '<i class="fa fa-home"></i> Home'.html_safe, main_app.root_path, style: "text-decoration:none;#{'color:#e6e1c9' if controller_name == 'home' && action_name == 'index'}" %>
      </li>
      <% if @pages.present? %>
        <% @pages.each do |page| %>
          <% if page.permalink == 'Category' %>
            <li id="menu-item-19" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children ot-dropdown <%= 'menu_active' if (action_name == 'wheat' || action_name == 'maize' || action_name == 'rice' || action_name == 'pulses' || action_name == 'jute' || action_name == 'sugarcane' || action_name == 'nuts' || action_name == 'sand' || action_name == 'seasons') %>">
              <%= link_to page.name.force_encoding("utf-8"), '#', style: "text-decoration:none;#{'color:#e6e1c9' if (action_name == 'wheat' || action_name == 'maize' || action_name == 'rice' || action_name == 'pulses' || action_name == 'jute' || action_name == 'sugarcane' || action_name == 'nuts' || action_name == 'sand' || action_name == 'seasons') }" %>
              <ul class="sub-menu">
                <li id="menu-item-547" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children ot-dropdown">
                  <a href="#" id='crop-menu' style='text-decoration:none;'>Crops
                    <i class="fa fa-angle-double-right fa-fw"></i></a>
                  <ul class="sub-menu crop-sub">
                    <li id="menu-item-554" class="menu-item menu-item-type-custom menu-item-object-custom">
                      <a href="<%= wheat_pages_path %>" style='text-decoration:none;'>Wheat </a>
                    </li>
                    <li id="menu-item-548" class="menu-item menu-item-type-custom menu-item-object-custom">
                      <a href="<%= maize_pages_path %>" style='text-decoration:none;'>Maize </a>
                    </li>
                    <li id="menu-item-564" class="menu-item menu-item-type-custom menu-item-object-custom">
                      <a href="<%= rice_pages_path %>" style='text-decoration:none;'>Rice </a>
                    </li>
                    <li id="menu-item-549" class="menu-item menu-item-type-custom menu-item-object-custom">
                      <a href="<%= pulses_pages_path %>" style='text-decoration:none;'>Pulses </a>
                    </li>
                    <li id="menu-item-550" class="menu-item menu-item-type-custom menu-item-object-custom">
                      <a href="<%= jute_pages_path %>" style='text-decoration:none;'>Jute </a>
                    </li>
                    <li id="menu-item-551" class="menu-item menu-item-type-custom menu-item-object-custom">
                      <a href="<%= sugarcane_pages_path %>" style='text-decoration:none;'>Sugarcane </a>
                    </li>
                  </ul>
                </li>
                <li id="menu-item-553" class="menu-item menu-item-type-custom menu-item-object-custom">
                  <a href="<%= nuts_pages_path %>" style='text-decoration:none;'>Nuts</a>
                </li>
                <li id="menu-item-552" class="menu-item menu-item-type-custom menu-item-object-custom">
                  <a href="<%= sand_pages_path %>" style='text-decoration:none;'>Sand </a>
                </li>
                <li id="menu-item-530" class="menu-item menu-item-type-custom menu-item-object-custom">
                  <a href="<%= seasons_pages_path %>" style='text-decoration:none;'> Seasons </a>
                </li>
              </ul>
            </li>
          <% elsif page.permalink == 'Investment' %>
            <li id="menu-item-221" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children ot-dropdown <%= 'menu_active' if (action_name == 'debt_relif' || action_name == 'short_term_loan' || action_name == 'midloan' || action_name == 'agri_banking' || action_name == 'agri_credit') %>">
              <%= link_to page.name.force_encoding("utf-8"), '#', style: "text-decoration:none; #{'color:#e6e1c9' if (action_name == 'debt_relif' || action_name == 'short_term_loan' || action_name == 'midloan' || action_name == 'agri_banking' || action_name == 'agri_credit') }" %>
              <ul class="sub-menu">
                <li id="menu-item-558" class="menu-item menu-item-type-custom menu-item-object-custom">
                  <a href="http://dbie.rbi.org.in/InfoViewApp/MOFSelectParam.jsp" target='_blank' style='text-decoration:none;'>Branch
                    Locator </a>
                </li>
                <li id="menu-item-559" class="menu-item menu-item-type-custom menu-item-object-custom">
                  <a href="<%= debt_relif_pages_path %>" style='text-decoration:none;'>Debt Relief</a>
                </li>
                <li id="menu-item-560" class="menu-item menu-item-type-custom menu-item-object-custom">
                  <a href="<%= short_term_loan_pages_path %>" style='text-decoration:none;'>Short Term Investment </a>
                </li>
                <li id="menu-item-561" class="menu-item menu-item-type-custom menu-item-object-custom">
                  <a href="<%= midloan_pages_path %>" style='text-decoration:none;'>Mid/Long Term Loans </a>
                </li>
                <li id="menu-item-562" class="menu-item menu-item-type-custom menu-item-object-custom">
                  <a href="<%= agri_banking_pages_path %>" style='text-decoration:none;'>Agriculture Banking</a>
                </li>
                <li id="menu-item-563" class="menu-item menu-item-type-custom menu-item-object-custom">
                  <a href="<%= agri_credit_pages_path %>" style='text-decoration:none;'>Agriculture Credit</a>
                </li>
              </ul>
            </li>
          <% elsif page.permalink == 'Forum' %>
            <li id="menu-item-505" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children ot-dropdown <%= 'menu_active' if action_name == 'Forum' %>">
              <%= link_to page.name.force_encoding("utf-8"), forem_path, style: "text-decoration:none; #{'color:#e6e1c9' if action_name == 'Forum' }" %>
            </li>
          <% elsif page.permalink == 'Education' %>
            <li id="menu-item-255" class="menu-item menu-item-type-post_type menu-item-object-page <%= 'menu_active' if action_name == 'education' %>">
              <%= link_to page.name.capitalize.force_encoding("utf-8"), education_pages_path, style: "text-decoration:none; #{'color:#e6e1c9' if action_name == 'education' }" %>
            </li>
          <% else %>
            <li id="menu-item-21" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children ot-dropdown <%= 'menu_active' if page.permalink == params[:id] %>">
              <%= link_to page.name.force_encoding("utf-8"), page_path(page.permalink), style: "text-decoration:none; #{'color:#e6e1c9' if page.permalink == params[:id] }" %>
            </li>
          <% end %>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

<style type="text/css">
  .forecast {
    position: relative;
    z-index: 1;
    line-height: 115%;
    color: #e6dfba;
  }

  .menu_active {
    background-color: #3c1805;
    color: #e6e1c9;
    text-shadow: none;
  }
</style>