config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {:omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations"}

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Forem::Engine, :at => '/forum'

  root 'home#index'
  resources :pages do
    collection do
      get 'category'
      get 'states'
      get 'reference'
      get 'wheat'
      get 'maize'
      get 'rice'
      get 'pulses'
      get 'jute'
      get 'sugarcane'
      get 'nuts'
      get 'sand'
      get 'seasons'
      get 'debt_relif'
      get 'short_term_loan'
      get 'midloan'
      get 'agri_banking'
      get 'agri_credit'
      get 'populate_state'
      get 'education'
    end
  end
  resources :states

offline = Rack::Offline.configure :cache_interval => 120 do 
  cache ActionController::Base.helpers.asset_path("application.css")
  cache ActionController::Base.helpers.asset_path("application.js")
  cache ActionController::Base.helpers.asset_path("desktop.css")
  cache ActionController::Base.helpers.asset_path("desktopd7b7.css")
  cache ActionController::Base.helpers.asset_path("ipad.css")
  cache ActionController::Base.helpers.asset_path("ipadv.css")
  cache ActionController::Base.helpers.asset_path("phonehorizontal.css")
  cache ActionController::Base.helpers.asset_path("phonevertical.css")
  cache ActionController::Base.helpers.asset_path("themes/alertnate-texture-body-bottom.png")
  cache ActionController::Base.helpers.asset_path("themes/alertnate-texture-body-full-bottom.png")
  cache ActionController::Base.helpers.asset_path("themes/alertnate-texture-body-full-top.png")
  cache ActionController::Base.helpers.asset_path("themes/alertnate-texture-body-full.jpg")
  cache ActionController::Base.helpers.asset_path("themes/alertnate-texture-body-top.png")
  cache ActionController::Base.helpers.asset_path("themes/alertnate-texture-body.jpg")
  cache ActionController::Base.helpers.asset_path("themes/background-overlay.png")
  cache ActionController::Base.helpers.asset_path("themes/background-texture-1.jpg")
  cache ActionController::Base.helpers.asset_path("themes/coupon-texture-1.jpg")
  cache ActionController::Base.helpers.asset_path("themes/content-background.jpg")
  cache ActionController::Base.helpers.asset_path("themes/header-texture-1.jpg")
  cache ActionController::Base.helpers.asset_path("themes/main-menu-texture-1.jpg")
  cache ActionController::Base.helpers.asset_path("themes/coupon-overlay.png")
  cache ActionController::Base.helpers.asset_path("agri-snapshot.png")
  cache ActionController::Base.helpers.asset_path("agri_credit.jpg")
  cache ActionController::Base.helpers.asset_path("debt.jpg")
  cache ActionController::Base.helpers.asset_path("education.jpg")
  cache ActionController::Base.helpers.asset_path("facebook.png")
  cache ActionController::Base.helpers.asset_path("fb-logo.png")
  cache ActionController::Base.helpers.asset_path("growth.jpg")
  cache ActionController::Base.helpers.asset_path("home.jpg")
  cache ActionController::Base.helpers.asset_path("indiarice.png")
  cache ActionController::Base.helpers.asset_path("jute.jpg")
  cache ActionController::Base.helpers.asset_path("loans.jpg")
  cache ActionController::Base.helpers.asset_path("logo.png")
  cache ActionController::Base.helpers.asset_path("maize.jpg")
  cache ActionController::Base.helpers.asset_path("maizeindia.png")
  cache ActionController::Base.helpers.asset_path("midloan.jpg")
  cache ActionController::Base.helpers.asset_path("nuts.jpg")
  cache ActionController::Base.helpers.asset_path("pulses.jpg")
  cache ActionController::Base.helpers.asset_path("rice.jpg")
  cache ActionController::Base.helpers.asset_path("sands.jpg")
  cache ActionController::Base.helpers.asset_path("season.jpg")
  cache ActionController::Base.helpers.asset_path("spices.jpg")
  cache ActionController::Base.helpers.asset_path("sugarcane.jpg")
  cache ActionController::Base.helpers.asset_path("wheat.jpg")


network "/"
end


get "/application.manifest" => offline


end

app/views/shared/popup/_sign_in.html.erb
<div class="modal" id="sign-in-modal" tabindex="-2" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> Sign In </h4>
      </div>
      <div class="modal-body">
        <div class='row'>
        <div class="col-md-8 col-centered" style='margin-left: 80px;'>
          <%= link_to image_tag("facebook.png", :border => 0), main_app.user_omniauth_authorize_path(:facebook), style: 'margin-left: 8%;' %>
          <br>

          <h3 style='text-align:center;'>Or </h3>
          
          <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <div class="form-group" style='text-align: left;'>
              <%= f.label :email, class: "control-label" %><br/>
              <%= f.email_field :email, autofocus: true, class: 'form-control' %>
            </div>
            <div class="form-group" style='text-align: left;'>
              <%= f.label :password, class: "control-label" %><br/>
              <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
            </div>
            <% if devise_mapping.rememberable? -%>
              <div class="form-group" style='text-align: left;'>
                <%= f.check_box :remember_me %>
                <%= f.label :remember_me, class: "control-label" %>
              </div>
            <% end -%>
            <div class="actions">
              <%= f.submit "Log in", class: 'btn btn-primary' %>
            </div>
          <% end %>
          <%= render "devise/shared/links" %>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>
<style type="text/css">
  /*.modal{
    left: 2%;
  }*/
</style>

app/views/shared/popup/_sign_up.html.erb
<div class="modal" id="sign-up-modal" tabindex="-2" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> Sign Up </h4>
      </div>
      <div class="modal-body" style='height: 880px;'>
        <div class="col-md-8 col-centered" style='margin-left: 80px;'>
          <%= link_to image_tag("fb-logo.png", size: '280x50', :border => 0), main_app.user_omniauth_authorize_path(:facebook) %>
          <br>
          <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
            <%= devise_error_messages! %>
            <div class="form-group" style='text-align: left;'>
              <%= f.label :name, class: "control-label" %><br/>
              <%= f.text_field :name, autofocus: true, class: 'form-control', style: 'width: 100%;' %>
            </div>

            <div class="form-group" style='text-align: left;'>
              <%= f.label :email, class: "control-label" %><br/>
              <%= f.email_field :email, class: 'form-control' %>
            </div>

            <div class="form-group" style='text-align: left;'>
              <%= f.label :password, class: "control-label" %>
              <% if @minimum_password_length %>
                <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %><br/>
              <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
            </div>
            <div class="form-group" style='text-align: left;'>
              <%= f.label :password_confirmation, class: "control-label" %><br/>
              <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
            </div>
            <div class="form-group" style='text-align: left;'>
              <%= f.label :dob, 'Date of Birth', class: "control-label" %><br/>
              <%= f.text_field :dob, class: 'form-control', style: 'width: 100%;' %>
            </div>
            <div class="form-group" style='text-align: left;'>
              <%= f.label :mobile, class: "control-label" %><br/>
              <%= f.text_field :mobile, class: 'form-control', style: 'width: 100%;' %>
            </div>
            <div class="form-group" style='text-align: left;'>
              <%= f.label :address, class: "control-label" %><br/>
              <%= f.text_field :address, class: 'form-control', style: 'width: 100%;' %>
            </div>
            <div class="form-group" style='text-align: left;'>
              <%= f.label :country, class: "control-label" %><br/>
              <%= f.country_select :country, {prompt: '--Please select country--'}, {class: 'form-control', onchange: "pick_state(this,#{params[:locale].to_json.html_safe});"} %>
            </div>
            <div class="form-group" style='text-align: left;'>
              <%= f.label :state, class: "control-label" %><br/>
              <%= f.select :state, options_for_select(['']), {prompt: '--Please select state--'}, {class: 'form-control'} %>
            </div>
            <div class="actions">
              <%= f.submit "Sign up", class: 'btn btn-primary' %>
            </div>
          <% end %>

          <%= render "devise/shared/links" %>


        </div>
      </div>
    </div>
  </div>
</div>
<style type="text/css">
  .modal {
    left: 2%;
  }
</style>
<script type="text/javascript">
  $(document).ready(function () {
    $('#user_dob').datepicker({
      format: 'dd-mm-yyyy',
      startDate: '+0d',
      todayHighlight: true,
      clearBtn: true,
      autoclose: true
    });
  });

  function pick_state(element) {
    var country = element.value;
    $.ajax({
      url: '/pages/populate_state',
      method: 'get',
      data: {country_id: country}
    }).done(function (data) {
      $('#user_state').html(data);
      $('#user_state').addClass('form-control');
    });
  }
</script>